version: '2'
services:
    webserver:
        image: ***.dkr.ecr.ap-southeast-2.amazonaws.com/tcslearnersclub:dev
        cpu_shares: 50
        mem_limit: 2048576000
        ports:
            - "8080:80"
        command: webserver
        logging:
          driver: awslogs
          options:
            awslogs-group: datalab-wfms
            awslogs-region: ap-southeast-1
            awslogs-stream-prefix: datalab-wfms-webserver
  
